version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    depends_on:
      - db
    image: php:8.1-apache
    volumes:
      - ./php:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - ./.docker/db:/docker-entrypoint-initdb.d
      - ./.docker/db/mysql:/var/lib/mysql